'use client'; 

import { Geist, Geist_Mono } from "next/font/google";
import "./index.css";

import { ThemeProvider, createTheme } from '@mui/material/styles';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const theme = createTheme({
  typography: {
    fontFamily: 'Poppins, Arial, sans-serif',
  },
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  /*window.addEventListener("error", (event) => {
      reportError({
        type: "error",
        message: event.message,
        file: event.filename,
        line: event.lineno,
        column: event.colno,
        stack: event.error?.stack,
      });
    });

window.addEventListener("unhandledrejection", (event) => {
      reportError({
        type: "unhandledrejection",
        message: event.reason?.message || "Unhandled rejection",
        stack: event.reason?.stack || event.reason,
      });
    });*/
 // }, []);
  
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
       <ThemeProvider theme={theme}>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
